spring:
  profiles:
    active: prod
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  jpa:
    hibernate:
      ddl-auto: update
    #        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

discodeit:
  storage:
    type: ${STORAGE_TYPE:local}  # local | s3 (기본값: local)
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers   # 요구 엔드포인트만 노출
  endpoint:
    health:
      show-details: always                     # /actuator/health 상세 표시
  info:
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: "1.7.0"
    spring-boot: "3.4.0"
    java: "17"
  datasource:
    url: "${spring.datasource.url:discodeit}"
    driver: "${spring.datasource.driver-class-name:postgresql}"
  jpa:
    ddl-auto: "${spring.jpa.hibernate.ddl-auto:validate}"
  storage:
    type: "${discodeit.storage.type:local}"
    path: "${discodeit.storage.local.root-path:.discodeit/storage}"
  multipart:
    max-file-size: "${spring.servlet.multipart.max-file-size}"
    max-request-size: "${spring.servlet.multipart.max-request-size}"


logging:
  level:
    root: info
