version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        PROJECT_VERSION: ${PROJECT_VERSION}
    container_name: spring-app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      #DATABASE
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      #STORAGE
      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_LOCAL_ROOT_PATH: ${STORAGE_LOCAL_ROOT_PATH}
      #AWS
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_PRESIGNED_URL_EXPIRATION: ${AWS_S3_PRESIGNED_URL_EXPIRATION}
      JVM_OPTS: ${JVM_OPTS}
    ports:
      - "${APP_PORT}:${SERVER_PORT}"
    volumes:
      - app-storage:/app/.discodeit/storage
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  app-storage:
    driver: local
