user  nginx;
worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # ============================================================
    # NGINX 로드밸런싱 전략
    # ============================================================

    # Round Robin (기본값) - 아무 지시어도 없으면 자동 적용
    #upstream backend_app {
    #     server backend:80;
    #}

    # Least Connections - 현재 연결 수가 가장 적은 서버 선택
    # upstream backend_app {
    #     least_conn;
    #     server backend-1:8080;
    #     server backend-2:8080;
    #     server backend-3:8080;
    # }

    # IP Hash - 동일한 클라이언트 IP는 항상 같은 서버로
    upstream backend_app {
        ip_hash;
        server backend:80;
        #server backend-2:80;
        #server backend-3:8080;
    }

    #  Weight - 특정 서버에 더 많은 트래픽 부여
    # upstream backend_app {
    #     server backend-1:8080 weight=3;
    #     server backend-2:8080 weight=1;
    #     server backend-3:8080 weight=1;
    # }

    # ============================================================


    server {
        listen 80;
        server_name _;

        location /api/ {
            proxy_pass http://backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header X-Upstream-Server $upstream_addr;
        }

        location /api/sse {
            proxy_pass http://backend_app;
            proxy_http_version 1.1;
            add_header X-Upstream-Server $upstream_addr;
        }

        location /ws/ {
            proxy_pass http://backend_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            add_header X-Upstream-Server $upstream_addr;
        }

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}
